services:
  portifolio-db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_portifolio:/var/lib/postgresql/data
    ports:
      - 5332:5432
    restart: always
    networks:
        - portifolio-networks
  portifolio-django:
      build: 
        context: .
      container_name: portifolio-django
      env_file:
        - .env
      ports:
        - 8000:8000
      depends_on:
        - portifolio-db
      restart: always
      networks:
        - portifolio-networks

volumes:
  postgres_data_portifolio:

networks:
  portifolio-networks:
    external: true
      
      